name: 'Render Template'

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

jobs:
  deploy:
    name: 'Render'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.3.0

      - uses: ./
        name: Render Template
        id: render-template
        with:
          template: '.github/pr-comment-template.hbs'
          inputs: |
            {
              "firstName":"Bob",
              "lastName":"Marley"
            }

      - name: Test Rendered Template
        run: |
          TRIMMED_OUTPUT=$(echo "$OUTPUT" | tr -d '\n')
          EXPECTED="<p>Bob Marley</p>"
          echo "Template: $TRIMMED_OUTPUT"
          echo "Expected: $EXPECTED"
          if [ "$TRIMMED_OUTPUT" != "$EXPECTED" ]; then
            echo "Template does not match."
            exit 1
          fi
        env:
          OUTPUT: ${{ steps.render-template.outputs.result }}
